apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: ibm-preprod-operator-group
  namespace: preprod
  annotations:
    argocd.argoproj.io/sync-wave: "110"
spec:
  targetNamespaces:
  - preprod